server:
  connection-timeout: 80000
  undertow:
    buffer-size: 8192
    buffers-per-region: 8192
    direct-buffers: true
    no-request-timeout: 60000
    max-http-post-size: 4096
  compression:
    enable: true
    mime-types: >-
      text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
spring: 
  sleuth:
    sampler:
      probability: 1
  datasource:
    driverClassName: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://mxd1.mx.bsch:5023/DSN:sslConnection=false;
    testWhileIdle: true
    validationQuery: SELECT 1
    username: DEIFTKMG
    password: 'GX38NTEF'
    hikari:
      maximumPoolSize: 50
      idleTimeout: 600000
      poolName: JPAHikariCustomer
      maxLifetime: 3600000
      connectionTimeout: 25000
      leak-detection-threshold: 60000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
  output:
    ansi:
      enabled: always
logging:
  level:
    root: INFO
    mx.santander.customerproductfees: INFO
    mx.santander.tokenmanager: INFO
customerproductfees-setting:
  queueDestination: TKNM.QR.REQUEST.D
  replyQueue: TKNM.QL.ANSWER.D
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    health:
      sensitive: false
    web:
      exposure:
        include: '*'
  health:
    rabbit: 
      enabled: false
    consul: 
      enabled: false
    db:
      enabled: false
    defaults:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
